#!/usr/bin/env bash
# Cross-compile TinyCC (libtcc.a) for Android aarch64
#
# Usage: ./scripts/build-tinycc.sh
#
# Bun uses TinyCC for its built-in C compiler. We need to cross-compile
# libtcc.a as a static library for Android aarch64.
#
# Source: oven-sh/tinycc (Bun's fork of TinyCC)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/env.sh"

TINYCC_COMMIT="${TINYCC_COMMIT:-b91835d8701523e895a2b447713630069514e291}"
TINYCC_SRC="${WORK_DIR}/tinycc-src"
TINYCC_BUILD="${TINYCC_SRC}/build-android"

echo "=== Building TinyCC (libtcc.a) for Android ${ANDROID_ARCH} ==="

# Check if already built and installed
if [ -f "$WEBKIT_OUTPUT/lib/libtcc.a" ]; then
    echo ">>> libtcc.a already exists at $WEBKIT_OUTPUT/lib/libtcc.a"
    ls -la "$WEBKIT_OUTPUT/lib/libtcc.a"
    exit 0
fi

# Clone TinyCC source
if [ ! -d "$TINYCC_SRC/.git" ]; then
    echo ">>> Cloning TinyCC at commit ${TINYCC_COMMIT}..."
    mkdir -p "$TINYCC_SRC"
    cd "$TINYCC_SRC"
    git init
    git remote add origin https://github.com/oven-sh/tinycc.git
    git fetch --depth=1 origin "${TINYCC_COMMIT}"
    git checkout FETCH_HEAD
else
    echo ">>> TinyCC source already exists at $TINYCC_SRC"
fi

# Build libtcc.a
echo ">>> Compiling TinyCC for Android aarch64..."
rm -rf "$TINYCC_BUILD"
mkdir -p "$TINYCC_BUILD"

# Arch-dependent sources + config
cd "$TINYCC_SRC"
if [ "$ANDROID_ARCH" = "aarch64" ]; then
    ARCH_SOURCES=(arm64-gen.c arm64-link.c arm-asm.c)
    ARCH_DEFINE="-DTCC_TARGET_ARM64"
else
    ARCH_SOURCES=()
    for f in x86_64-gen.c x86_64-link.c i386-asm.c i386-link.c; do
        [ -f "$TINYCC_SRC/$f" ] && ARCH_SOURCES+=("$f")
    done
    [ ${#ARCH_SOURCES[@]} -eq 0 ] && { echo "ERROR: no x86_64 sources found in this TinyCC tree"; exit 1; }
    ARCH_DEFINE="-DTCC_TARGET_X86_64"
    echo ">>> x86_64 sources: ${ARCH_SOURCES[*]}"
fi

SOURCES=(
    libtcc.c
    tccpp.c
    tccgen.c
    tccelf.c
    tccasm.c
    tccrun.c
    "${ARCH_SOURCES[@]}"
)

# Create minimal config.h (normally generated by ./configure).
# NOTE: $ARCH_DEFINE is a compiler-flag string — it must NOT appear inside
# config.h; the config gets a proper #define line instead.
if [ "$ANDROID_ARCH" = "aarch64" ]; then
    ARCH_CFG="#define TCC_TARGET_ARM64 1"
else
    ARCH_CFG="#define TCC_TARGET_X86_64 1"
fi
cat > "$TINYCC_SRC/config.h" <<CONFEOF
#define TCC_VERSION "0.9.27"
$ARCH_CFG
#define CONFIG_TCC_CROSSPREFIX ""
#define CONFIG_TCCDIR "/data/data/com.termux/files/usr/lib/tcc"
CONFEOF
echo ">>> config.h contents:"
cat "$TINYCC_SRC/config.h"
echo ">>> TCC_TARGET leakage in environment:"
env | grep -i "TCC_TARGET" || echo "  (none)"

for src in "${SOURCES[@]}"; do
    echo "  Compiling $src..."
    $ANDROID_CC \
        -O2 -fPIC -Wall -fno-strict-aliasing $ANDROID_ARCH_CFLAGS \
        -DONE_SOURCE=0 \
        '-DTCC_LIBTCC1="\0"' \
        '-DTCC_VERSION="0.9.27"' \
        -UTCC_TARGET_ARM -UTCC_TARGET_ARM64 -UTCC_TARGET_I386 -UTCC_TARGET_RISCV64 \
        $ARCH_DEFINE \
        -I"$TINYCC_SRC" \
        -c "$src" \
        -o "$TINYCC_BUILD/${src%.c}.o"
done

echo ">>> Creating libtcc.a..."
$ANDROID_AR rcs "$TINYCC_BUILD/libtcc.a" "$TINYCC_BUILD"/*.o

# Install to webkit-android output (where Bun's CMake expects it)
mkdir -p "$WEBKIT_OUTPUT/lib"
cp "$TINYCC_BUILD/libtcc.a" "$WEBKIT_OUTPUT/lib/"

echo ""
echo "=== TinyCC build complete ==="
echo "Library: $WEBKIT_OUTPUT/lib/libtcc.a"
ls -la "$WEBKIT_OUTPUT/lib/libtcc.a"
file "$WEBKIT_OUTPUT/lib/libtcc.a"
